Repository Dragonlord1005/ai-mentalhealth, pull requests merged in 2025-02, with the labels that each got.

#54 Revert "Bump @fastify/static from 8.0.4 to 8.1.0"
  package.json
  pnpm-lock.yaml
Labels: size/M

#64 Colors abstracted
  src/components/Navbar/Navbar.module.css
  src/components/Navbar/Navbar.tsx
  src/components/ThemeToggle/ThemeToggle.module.css
  src/components/ThemeToggle/ThemeToggle.tsx
  src/components/chatbot/chatbot.module.css
  src/components/chatbot/chatbot.tsx
  src/global.css
  src/root.tsx
  src/routes/index.tsx
Labels: size/L

#61 Colors
  src/components/Navbar/Navbar.module.css
  src/components/Navbar/Navbar.tsx
  src/components/ThemeToggle/ThemeToggle.module.css
  src/components/ThemeToggle/ThemeToggle.tsx
  src/components/chatbot/chatbot.module.css
  src/components/chatbot/chatbot.spec.tsx
  src/components/chatbot/chatbot.tsx
  src/global.css
  src/root.tsx
  src/routes/index.spec.tsx
  src/routes/index.tsx
Labels: size/L

#74 Merge current main into prod
  Dockerfile
  package.json
  pnpm-lock.yaml
  src/components/Navbar/Navbar.module.css
  src/components/Navbar/Navbar.tsx
  src/components/ThemeToggle/ThemeToggle.module.css
  src/components/ThemeToggle/ThemeToggle.tsx
  src/components/chatbot/chatbot.module.css
  src/components/chatbot/chatbot.spec.tsx
  src/components/chatbot/chatbot.tsx
  src/global.css
  src/root.tsx
  src/routes/index.spec.tsx
  src/routes/index.tsx
Labels: size/XL
